# Generated by Django 4.1.5 on 2023-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloobloopapp", "0003_add_empty_conversations_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileitem",
            name="conversations",
        ),
        migrations.AddField(
            model_name="conversationitem",
            name="users",
            field=models.ManyToManyField(to="bloobloopapp.profileitem"),
        ),
    ]
