# Generated by Django 4.1.5 on 2023-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloobloopapp", "0004_change_many_to_many_from_profile_to_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileitem",
            name="conversations",
            field=models.ManyToManyField(
                blank=True, to="bloobloopapp.conversationitem"
            ),
        ),
    ]
