# Generated by Django 4.1.5 on 2023-03-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bloobloopapp", "0006_add_messages_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageitem",
            name="conversation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="bloobloopapp.conversationitem",
            ),
        ),
        migrations.AlterField(
            model_name="messageitem",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="bloobloopapp.profileitem",
            ),
        ),
    ]
