# Generated by Django 4.1.5 on 2023-03-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bloobloopapp", "0007_add_messages_to_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageitem",
            name="conversation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="bloobloopapp.conversationitem",
            ),
            preserve_default=False,
        ),
    ]
