name: Deploy Project

on:
  push:
    branches:
      - deployment
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0
      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1.144.0
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: "Install SSH key"
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Add known hosts"
        run: |
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts
      - name: "Deploy"
        env:
          DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          bundle exec cap apps:api:production deploy
          bundle exec cap apps:frontend:production deploy
